language: cpp

compiler:
  - gcc
#  - clang

env:
  - BUILD_CONFIG=Debug
  - BUILD_CONFIG=Release

before_install:
  # pull in some common scripts for setting up Travis CI build environment
  - git clone --depth=1 https://github.com/Kosta-Github/travis-setup.git
  - sudo travis-setup/update-environment.sh
  - sudo travis-setup/update-gcc-latest.sh

install:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIG

script:
  - make -k && ctest -V --timeout 60

